"""Fine-tune a pretrained U-Net-style model on the dataset generated by prepare.py.

What this script does
---------------------
- Reads samples.csv produced by your dataset generator.
- Builds input tensors from:
  masked_image, hole_mask, land_mask, drift_prev (optional),
  plus coordinate channels x/y and a normalized time channel.
- Decodes the grayscale class encoding back to class IDs 0..N.
- Fine-tunes a pretrained ResNet34 encoder U-Net with cross-entropy loss.
- Supports multi-GPU training with torchrun / DDP.

Why this is a good fit
----------------------
Your generated data is not natural RGB imagery, so training from scratch is usually
wasteful. A pretrained encoder still helps, while the decoder learns the local
ice-map reconstruction task.

Example
-------
# 4 GPUs
torchrun --nproc_per_node=4 finetune_vizard_inpainting.py \
  --data-root /path/to/dataset \
  --num-classes 9 \
  --epochs 60 \
  --batch-size 8 \
  --lr 3e-4 \
  --amp \
  --save-dir /path/to/checkpoints

Notes
-----
- The script assumes the dataset structure from prepare.py:
  output_root/{train,val,test}/{version}/{subdir}/*.tif and samples.csv
- Land pixels are ignored in the loss by default.
- If drift_prev is missing, the corresponding channel is filled with zeros.
- If you want to do masked-image completion only inside holes, that is already
  encouraged by the loss weighting.
"""

from __future__ import annotations

import argparse
import csv
import math
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import rasterio
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, DistributedSampler
from torchvision.models import ResNet34_Weights, resnet34
from tqdm import tqdm


# -----------------------------
# Utilities
# -----------------------------


def read_tif_1ch(path: Path) -> np.ndarray:
    with rasterio.open(path) as src:
        arr = src.read(1)
    return arr


def decode_encoded_classes_u8(img: np.ndarray, num_classes: int) -> np.ndarray:
    """Inverse of prepare.py::encode_classes_u8.

    Values are expected to be one of the linearly spaced codes in [1, 255].
    Any zero stays zero. Non-zero values are mapped to the nearest class.
    """
    img = img.astype(np.uint8)
    out = np.zeros_like(img, dtype=np.int64)
    codes = np.rint(np.linspace(1, 255, num_classes)).astype(np.int64)
    nonzero = img > 0
    if np.any(nonzero):
        flat = img[nonzero].astype(np.int64)[:, None]
        dists = np.abs(flat - codes[None, :])
        out[nonzero] = dists.argmin(axis=1) + 1
    return out


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


# -----------------------------
# Dataset
# -----------------------------


@dataclass
class SampleRow:
    split: str
    version: str
    sample_id: str
    source_file: str
    patch_index: int
    time_norm: float
    top: int
    left: int
    patch_size: int
    drift_prev: int
    drift_uv: int


class VizardDataset(Dataset):
    def __init__(
        self,
        data_root: Path,
        split: str,
        num_classes: int,
        use_drift_prev: bool = True,
        min_time_norm: float = 0.0,
        max_time_norm: float = 1.0,
    ) -> None:
        self.data_root = data_root
        self.split = split
        self.num_classes = num_classes
        self.use_drift_prev = use_drift_prev
        self.rows: List[SampleRow] = []

        samples_csv = data_root / "samples.csv"
        if not samples_csv.exists():
            raise FileNotFoundError(f"Missing {samples_csv}")

        with open(samples_csv, "r", encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                if row["split"] != split:
                    continue
                t = float(row["time_norm"])
                if not (min_time_norm <= t <= max_time_norm):
                    continue
                self.rows.append(
                    SampleRow(
                        split=row["split"],
                        version=row["version"],
                        sample_id=row["sample_id"],
                        source_file=row["source_file"],
                        patch_index=int(row["patch_index"]),
                        time_norm=t,
                        top=int(row["top"]),
                        left=int(row["left"]),
                        patch_size=int(row["patch_size"]),
                        drift_prev=int(row["drift_prev"]),
                        drift_uv=int(row["drift_uv"]),
                    )
                )

        if not self.rows:
            raise RuntimeError(f"No rows found for split={split}")

    def __len__(self) -> int:
        return len(self.rows)

    def _p(self, row: SampleRow, subdir: str) -> Path:
        return self.data_root / row.split / row.version / subdir / f"{row.sample_id}.tif"

    def __getitem__(self, idx: int):
        row = self.rows[idx]
        orig = read_tif_1ch(self._p(row, "original"))
        masked = read_tif_1ch(self._p(row, "masked"))
        hole = read_tif_1ch(self._p(row, "masks")) > 0
        land = read_tif_1ch(self._p(row, "land_mask")) > 0
        if self.use_drift_prev and (self.data_root / row.split / row.version / "drift_prev" / f"{row.sample_id}.tif").exists():
            drift = read_tif_1ch(self._p(row, "drift_prev"))
        else:
            drift = np.zeros_like(masked)

        # Decode the grayscale encoding back to class IDs.
        target = decode_encoded_classes_u8(orig, self.num_classes)

        # Input normalization.
        masked_f = masked.astype(np.float32) / 255.0
        hole_f = hole.astype(np.float32)
        land_f = land.astype(np.float32)
        drift_f = drift.astype(np.float32) / 255.0

        h, w = masked.shape
        yy = np.linspace(-1.0, 1.0, h, dtype=np.float32)[:, None]
        xx = np.linspace(-1.0, 1.0, w, dtype=np.float32)[None, :]
        x_ch = np.repeat(xx, h, axis=0)
        y_ch = np.repeat(yy, w, axis=1)
        time_ch = np.full((h, w), np.float32(row.time_norm), dtype=np.float32)

        # Stack channels: [masked, hole, land, drift, x, y, time]
        x = np.stack([masked_f, hole_f, land_f, drift_f, x_ch, y_ch, time_ch], axis=0)

        # Loss mask: ignore land in the target.
        ignore = land.astype(np.int64)

        return torch.from_numpy(x), torch.from_numpy(target), torch.from_numpy(ignore), torch.from_numpy(hole.astype(np.float32))


# -----------------------------
# Model: lightweight U-Net with pretrained ResNet34 encoder
# -----------------------------


class DoubleConv(nn.Module):
    def __init__(self, in_ch: int, out_ch: int):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )

    def forward(self, x):
        return self.net(x)


class UpBlock(nn.Module):
    def __init__(self, in_ch: int, skip_ch: int, out_ch: int):
        super().__init__()
        self.up = nn.ConvTranspose2d(in_ch, out_ch, kernel_size=2, stride=2)
        self.conv = DoubleConv(out_ch + skip_ch, out_ch)

    def forward(self, x, skip):
        x = self.up(x)
        if x.shape[-2:] != skip.shape[-2:]:
            x = F.interpolate(x, size=skip.shape[-2:], mode="bilinear", align_corners=False)
        x = torch.cat([x, skip], dim=1)
        return self.conv(x)


class ResNet34UNet(nn.Module):
    def __init__(self, in_channels: int = 7, num_classes: int = 10):
        super().__init__()
        weights = ResNet34_Weights.IMAGENET1K_V1
        backbone = resnet34(weights=weights)

        # Adapt first conv to arbitrary input channels.
        old_conv = backbone.conv1
        backbone.conv1 = nn.Conv2d(
            in_channels,
            old_conv.out_channels,
            kernel_size=old_conv.kernel_size,
            stride=old_conv.stride,
            padding=old_conv.padding,
            bias=False,
        )
        with torch.no_grad():
            if in_channels >= 3:
                backbone.conv1.weight[:, :3].copy_(old_conv.weight)
                if in_channels > 3:
                    mean_w = old_conv.weight.mean(dim=1, keepdim=True)
                    for c in range(3, in_channels):
                        backbone.conv1.weight[:, c : c + 1].copy_(mean_w)
            else:
                backbone.conv1.weight.copy_(old_conv.weight[:, :in_channels])

        self.stem = nn.Sequential(
            backbone.conv1,
            backbone.bn1,
            backbone.relu,
        )
        self.maxpool = backbone.maxpool
        self.enc1 = backbone.layer1  # 64
        self.enc2 = backbone.layer2  # 128
        self.enc3 = backbone.layer3  # 256
        self.enc4 = backbone.layer4  # 512

        self.center = DoubleConv(512, 512)
        self.up4 = UpBlock(512, 256, 256)
        self.up3 = UpBlock(256, 128, 128)
        self.up2 = UpBlock(128, 64, 64)
        self.up1 = UpBlock(64, 64, 64)

        # One extra 2x upsample is needed because the ResNet stem already downsamples by 2.
        self.final_up = nn.Upsample(scale_factor=2, mode="bilinear", align_corners=False)
        self.head = nn.Sequential(
            nn.Conv2d(64, 64, 3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(64, num_classes, 1),
        )

    def forward(self, x):
        x0 = self.stem(x)           # /2
        x1 = self.enc1(self.maxpool(x0))  # /4
        x2 = self.enc2(x1)          # /8
        x3 = self.enc3(x2)          # /16
        x4 = self.enc4(x3)          # /32
        c = self.center(x4)
        d4 = self.up4(c, x3)
        d3 = self.up3(d4, x2)
        d2 = self.up2(d3, x1)
        d1 = self.up1(d2, x0)
        d0 = self.final_up(d1)      # back to input resolution
        return self.head(d0)


# -----------------------------
# Losses / metrics
# -----------------------------


def masked_cross_entropy(logits: torch.Tensor, target: torch.Tensor, ignore: torch.Tensor, hole: torch.Tensor, hole_weight: float = 2.0):
    """Cross-entropy with stronger weight inside holes and ignore on land."""
    # target: [B,H,W] class ids in 0..num_classes
    # ignore: [B,H,W] 1 on land -> ignore
    valid = ignore == 0
    if valid.sum() == 0:
        return logits.sum() * 0.0

    loss_map = F.cross_entropy(logits, target.long(), ignore_index=255, reduction="none")

    # Set ignored pixels to zero.
    loss_map = loss_map * valid.float()

    # Emphasize hole pixels.
    weights = torch.ones_like(loss_map)
    weights = torch.where(hole > 0.5, torch.full_like(weights, hole_weight), weights)
    weights = weights * valid.float()

    return (loss_map * weights).sum() / weights.sum().clamp_min(1.0)


@torch.no_grad()
def compute_pixel_accuracy(logits: torch.Tensor, target: torch.Tensor, ignore: torch.Tensor):
    pred = logits.argmax(dim=1)
    valid = ignore == 0
    correct = (pred == target) & valid
    total = valid.sum().item()
    if total == 0:
        return 0.0
    return correct.sum().item() / total


# -----------------------------
# Train / eval
# -----------------------------


def ddp_setup() -> Tuple[int, int, int]:
    world_size = int(os.environ.get("WORLD_SIZE", "1"))
    rank = int(os.environ.get("RANK", "0"))
    local_rank = int(os.environ.get("LOCAL_RANK", "0"))
    if world_size > 1:
        torch.distributed.init_process_group(backend="nccl")
        torch.cuda.set_device(local_rank)
    return world_size, rank, local_rank


def ddp_cleanup() -> None:
    if torch.distributed.is_available() and torch.distributed.is_initialized():
        torch.distributed.destroy_process_group()


@torch.no_grad()
def evaluate(model: nn.Module, loader: DataLoader, device: torch.device, amp: bool, num_classes: int):
    model.eval()
    total_loss = 0.0
    total_acc = 0.0
    total_iou = 0.0
    n_batches = 0

    for x, target, ignore, hole in tqdm(loader, desc="Val", leave=False):
        x = x.to(device, non_blocking=True)
        target = target.to(device, non_blocking=True)
        ignore = ignore.to(device, non_blocking=True)
        hole = hole.to(device, non_blocking=True)

        with torch.cuda.amp.autocast(enabled=amp):
            logits = model(x)
            loss = masked_cross_entropy(logits, target, ignore, hole)

        pred = logits.argmax(dim=1)
        valid = ignore == 0
        correct = ((pred == target) & valid).sum().item()
        total = valid.sum().item()
        acc = correct / total if total else 0.0

        # Mean IoU over classes excluding background 0 and ignored pixels.
        ious = []
        for c in range(1, num_classes + 1):
            pred_c = (pred == c) & valid
            tgt_c = (target == c) & valid
            inter = (pred_c & tgt_c).sum().item()
            union = (pred_c | tgt_c).sum().item()
            if union > 0:
                ious.append(inter / union)
        miou = float(np.mean(ious)) if ious else 0.0

        total_loss += loss.item()
        total_acc += acc
        total_iou += miou
        n_batches += 1

    return total_loss / max(1, n_batches), total_acc / max(1, n_batches), total_iou / max(1, n_batches)


def save_checkpoint(path: Path, model: nn.Module, optimizer: torch.optim.Optimizer, scheduler, epoch: int, best_metric: float, args: argparse.Namespace):
    ensure_dir(path.parent)
    state = {
        "epoch": epoch,
        "best_metric": best_metric,
        "model": model.module.state_dict() if hasattr(model, "module") else model.state_dict(),
        "optimizer": optimizer.state_dict(),
        "scheduler": scheduler.state_dict() if scheduler is not None else None,
        "args": vars(args),
    }
    torch.save(state, path)


def load_checkpoint(path: Path, model: nn.Module, optimizer: Optional[torch.optim.Optimizer] = None, scheduler=None, map_location="cpu"):
    ckpt = torch.load(path, map_location=map_location)
    sd = ckpt["model"]
    if hasattr(model, "module"):
        model.module.load_state_dict(sd, strict=True)
    else:
        model.load_state_dict(sd, strict=True)
    if optimizer is not None and "optimizer" in ckpt and ckpt["optimizer"] is not None:
        optimizer.load_state_dict(ckpt["optimizer"])
    if scheduler is not None and ckpt.get("scheduler") is not None:
        scheduler.load_state_dict(ckpt["scheduler"])
    return ckpt


# -----------------------------
# CLI
# -----------------------------


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--data-root", type=str, required=True, help="Root of dataset generated by prepare.py")
    p.add_argument("--save-dir", type=str, required=True)
    p.add_argument("--num-classes", type=int, default=9)
    p.add_argument("--epochs", type=int, default=60)
    p.add_argument("--batch-size", type=int, default=8)
    p.add_argument("--val-batch-size", type=int, default=8)
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--weight-decay", type=float, default=1e-4)
    p.add_argument("--amp", action="store_true")
    p.add_argument("--num-workers", type=int, default=16)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--resume", type=str, default="")
    p.add_argument("--freeze-encoder-epochs", type=int, default=2)
    p.add_argument("--hole-weight", type=float, default=2.0)
    p.add_argument("--grad-clip", type=float, default=1.0)
    p.add_argument("--save-every", type=int, default=1)
    p.add_argument("--precision", type=str, default="fp16", choices=["fp16", "bf16", "fp32"])
    return p.parse_args()


def set_seed(seed: int) -> None:
    torch.manual_seed(seed)
    np.random.seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = True


def main() -> None:
    args = parse_args()
    set_seed(args.seed)

    world_size, rank, local_rank = ddp_setup()
    is_main = rank == 0
    device = torch.device(f"cuda:{local_rank}" if torch.cuda.is_available() else "cpu")

    save_dir = Path(args.save_dir)
    if is_main:
        ensure_dir(save_dir)

    train_ds = VizardDataset(Path(args.data_root), split="train", num_classes=args.num_classes, use_drift_prev=True)
    val_ds = VizardDataset(Path(args.data_root), split="val", num_classes=args.num_classes, use_drift_prev=True)

    train_sampler = DistributedSampler(train_ds, shuffle=True) if world_size > 1 else None
    val_sampler = DistributedSampler(val_ds, shuffle=False) if world_size > 1 else None

    train_loader = DataLoader(
        train_ds,
        batch_size=args.batch_size,
        sampler=train_sampler,
        shuffle=(train_sampler is None),
        num_workers=args.num_workers,
        pin_memory=True,
        persistent_workers=args.num_workers > 0,
        drop_last=True,
    )
    val_loader = DataLoader(
        val_ds,
        batch_size=args.val_batch_size,
        sampler=val_sampler,
        shuffle=False,
        num_workers=max(2, args.num_workers // 2),
        pin_memory=True,
        persistent_workers=args.num_workers > 0,
        drop_last=False,
    )

    model = ResNet34UNet(in_channels=7, num_classes=args.num_classes + 1).to(device)

    # Freeze encoder BEFORE DDP wrapping to avoid "unused parameter" issues.
    def set_encoder_trainable(trainable: bool):
        core = model
        for module in [core.stem, core.maxpool, core.enc1, core.enc2, core.enc3, core.enc4]:
            for p in module.parameters():
                p.requires_grad = trainable

    set_encoder_trainable(False)

    if world_size > 1:
        # find_unused_parameters=True makes DDP robust if you freeze/unfreeze parts of the network.
        model = torch.nn.parallel.DistributedDataParallel(
            model,
            device_ids=[local_rank],
            output_device=local_rank,
            find_unused_parameters=True,
        )

    optimizer = torch.optim.AdamW((p for p in model.parameters() if p.requires_grad), lr=args.lr, weight_decay=args.weight_decay)

    steps_per_epoch = max(1, len(train_loader))
    total_steps = args.epochs * steps_per_epoch
    warmup_steps = max(100, int(0.03 * total_steps))

    def lr_lambda(step: int):
        core = model.module if hasattr(model, "module") else model
        for module in [core.stem, core.maxpool, core.enc1, core.enc2, core.enc3, core.enc4]:
            for p in module.parameters():
                p.requires_grad = trainable

    set_encoder_trainable(False)

    optimizer = torch.optim.AdamW((p for p in model.parameters() if p.requires_grad), lr=args.lr, weight_decay=args.weight_decay)

    steps_per_epoch = max(1, len(train_loader))
    total_steps = args.epochs * steps_per_epoch
    warmup_steps = max(100, int(0.03 * total_steps))

    def lr_lambda(step: int):
        if step < warmup_steps:
            return float(step + 1) / float(max(1, warmup_steps))
        progress = (step - warmup_steps) / max(1, total_steps - warmup_steps)
        return 0.5 * (1.0 + math.cos(math.pi * min(1.0, progress)))

    scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda=lr_lambda)

    scaler = torch.cuda.amp.GradScaler(enabled=args.amp and args.precision == "fp16")
    best_miou = -1.0
    start_epoch = 0
    global_step = 0

    if args.resume:
        ckpt = load_checkpoint(Path(args.resume), model, optimizer, scheduler, map_location="cpu")
        start_epoch = int(ckpt.get("epoch", 0)) + 1
        best_miou = float(ckpt.get("best_metric", -1.0))
        if is_main:
            print(f"Resumed from {args.resume} at epoch {start_epoch}, best_miou={best_miou:.4f}")

    for epoch in range(start_epoch, args.epochs):
        if train_sampler is not None:
            train_sampler.set_epoch(epoch)

        core = model.module if hasattr(model, "module") else model
        if epoch == args.freeze_encoder_epochs:
            set_encoder_trainable(True)
            optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
            scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda=lr_lambda)
            if is_main:
                print("Encoder unfrozen.")

        model.train()
        running_loss = 0.0
        running_acc = 0.0
        n_batches = 0

        pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{args.epochs}", disable=not is_main)
        optimizer.zero_grad(set_to_none=True)
        for x, target, ignore, hole in pbar:
            x = x.to(device, non_blocking=True)
            target = target.to(device, non_blocking=True)
            ignore = ignore.to(device, non_blocking=True)
            hole = hole.to(device, non_blocking=True)

            if args.amp and args.precision == "bf16":
                amp_context = torch.autocast(device_type="cuda", dtype=torch.bfloat16)
            elif args.amp and args.precision == "fp16":
                amp_context = torch.cuda.amp.autocast(enabled=True)
            else:
                amp_context = torch.autocast(device_type="cuda", enabled=False) if torch.cuda.is_available() else torch.cpu.amp.autocast(enabled=False)

            with amp_context:
                logits = model(x)
                loss = masked_cross_entropy(logits, target, ignore, hole, hole_weight=args.hole_weight)
                loss = loss / 1.0

            if scaler.is_enabled():
                scaler.scale(loss).backward()
                if args.grad_clip > 0:
                    scaler.unscale_(optimizer)
                    torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                if args.grad_clip > 0:
                    torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
                optimizer.step()
            optimizer.zero_grad(set_to_none=True)
            scheduler.step()
            global_step += 1

            with torch.no_grad():
                acc = compute_pixel_accuracy(logits, target, ignore)
            running_loss += loss.item()
            running_acc += acc
            n_batches += 1

            if is_main:
                pbar.set_postfix(loss=running_loss / n_batches, acc=running_acc / n_batches, lr=optimizer.param_groups[0]["lr"])

        # Validation on rank 0 only.
        if is_main:
            val_loss, val_acc, val_miou = evaluate(model, val_loader, device, amp=args.amp, num_classes=args.num_classes)
            print(f"Val: loss={val_loss:.4f} acc={val_acc:.4f} miou={val_miou:.4f}")

            if val_miou > best_miou:
                best_miou = val_miou
                save_checkpoint(save_dir / "best.pt", model, optimizer, scheduler, epoch, best_miou, args)
                print(f"Saved best.pt (miou={best_miou:.4f})")

            if (epoch + 1) % args.save_every == 0:
                save_checkpoint(save_dir / f"epoch_{epoch+1:03d}.pt", model, optimizer, scheduler, epoch, best_miou, args)

    if is_main:
        save_checkpoint(save_dir / "last.pt", model, optimizer, scheduler, args.epochs - 1, best_miou, args)
        print(f"Training finished. Best miou={best_miou:.4f}")

    ddp_cleanup()


if __name__ == "__main__":
    main()
